# Generated by Django 5.2.17 on 2026-09-28 00:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Blok Adı')),
                ('gender_type', models.CharField(choices=[('KIZ', 'Kız Öğrenci'), ('ERKEK', 'Erkek Öğrenci'), ('KARMA', 'İdari / Karma')], max_length=20, verbose_name='Yurt Tipi')),
                ('address', models.CharField(max_length=255, verbose_name='Adres / Konum')),
                ('total_rooms', models.PositiveIntegerField(default=120, verbose_name='Toplam Oda Sayısı')),
                ('capacity', models.PositiveIntegerField(default=480, verbose_name='Öğrenci Kapasitesi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bina Bloğu',
                'verbose_name_plural': 'Bina Blokları',
                'db_table': 'building_block',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Öğle Yemeği'), ('DINNER', 'Akşam Yemeği')], default='DINNER', max_length=20, verbose_name='Öğün')),
                ('soup', models.CharField(max_length=100, verbose_name='Çorba')),
                ('main_course', models.CharField(max_length=100, verbose_name='Ana Yemek')),
                ('side_dish', models.CharField(max_length=100, verbose_name='Yan Yemek / Pilav / Makarna')),
                ('extra', models.CharField(max_length=100, verbose_name='Tatlı / Meyve / Salata')),
                ('calories', models.PositiveIntegerField(default=850, verbose_name='Toplam Kalori (kcal)')),
                ('rating', models.FloatField(default=4.6, verbose_name='Memnuniyet Puanı')),
                ('review_count', models.PositiveIntegerField(default=142, verbose_name='Değerlendirme Sayısı')),
            ],
            options={
                'verbose_name': 'Yemekhane Menüsü',
                'verbose_name_plural': 'Yemekhane Menüleri',
                'db_table': 'cafeteria_menu',
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('department', models.CharField(max_length=100, verbose_name='İlgili Departman')),
                ('icon', models.CharField(default='build', max_length=50, verbose_name='İkon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tc_no', models.CharField(max_length=11, unique=True, verbose_name='T.C. Kimlik No')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('role', models.CharField(choices=[('ADMIN', 'Sistem Yöneticisi'), ('MANAGER', 'Yurt Müdürü / İdare'), ('STAFF', 'Birim Görevlisi / Personel'), ('STUDENT', 'Öğrenci')], default='STUDENT', max_length=20, verbose_name='Kullanıcı Rolü')),
                ('room_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oda No')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Personel / Admin Girişi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='dorm_app.buildingblock', verbose_name='Bağlı Olduğu Blok')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'db_table': 'app_user',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Duyuru Başlığı')),
                ('content', models.TextField(verbose_name='Duyuru Metni')),
                ('category', models.CharField(default='Genel', max_length=50, verbose_name='Kategori')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Acil Duyuru mu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Zamanı')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Yayınlayan')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='dorm_app.buildingblock', verbose_name='Hedef Blok (Boşsa Tüm Yurt)')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'db_table': 'announcement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50, verbose_name='Oda / Alan Numarası')),
                ('title', models.CharField(max_length=200, verbose_name='Şikayet Başlığı')),
                ('description', models.TextField(verbose_name='Detaylı Açıklama')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('IN_PROGRESS', 'İşleme Alındı'), ('RESOLVED', 'Çözüldü'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('LOW', 'Düşük'), ('NORMAL', 'Normal'), ('HIGH', 'Yüksek'), ('URGENT', 'Acil')], default='NORMAL', max_length=20, verbose_name='Öncelik')),
                ('resolution_note', models.TextField(blank=True, null=True, verbose_name='Çözüm / Süreç Notu')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözülme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Personel')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='dorm_app.buildingblock', verbose_name='Blok')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='dorm_app.category', verbose_name='Kategori')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Şikayetçi Öğrenci')),
            ],
            options={
                'verbose_name': 'Arıza & Şikayet',
                'verbose_name_plural': 'Arıza & Şikayetler',
                'db_table': 'complaint',
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('status', 'PENDING')), fields=['block', '-created_at'], name='idx_complaints_active_partial'), models.Index(fields=['student', '-created_at'], name='idx_student_complaints')],
            },
        ),
    ]
