# Generated by Django 5.2.17 on 2026-10-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yayından Kalkma Tarihi'),
        ),
    ]
